name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.15', '1.16', '1.17', '1.18', '1.19', '1.20' ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...